"""All constants for the display module.

Constants:
    GRAPHICS_ENGINE_NAME: str
    GRAPHICS_ENGINE_VERSION: ine
    REQUIRED_VULKAN_VERSION: int
    VALIDATION_LAYERS_ENABLED: bool
    VALIDATION_LAYERS: list[str]
"""

from vulkan import VK_KHR_SWAPCHAIN_EXTENSION_NAME, VK_MAKE_VERSION

from src.consts import BASE_DIR

GRAPHICS_ENGINE_NAME = "PyVulkan"
GRAPHICS_ENGINE_VERSION = VK_MAKE_VERSION(1, 0, 0)

REQUIRED_VULKAN_VERSION = VK_MAKE_VERSION(0, 1, 0)

VALIDATION_LAYERS_ENABLED = True
VALIDATION_LAYERS = [
    "VK_LAYER_KHRONOS_validation",
]

DEVICE_EXTENSIONS = [
    VK_KHR_SWAPCHAIN_EXTENSION_NAME,
]

VERTEX_SHADER_FILEPATH = BASE_DIR / "vert.spv"
FRAGMENT_SHADER_FILEPATH = BASE_DIR / "frag.spv"

RENDER_FENCE_TIMEOUT = 1_000_000_000 # 1s
